"""
Read more on event types here:
https://stripe.com/docs/api/events/types#event_types-customer.updated
"""
EVENT_OBJECT_TYPES = {
    "charge": (
        "charge.succeeded",
        "charge.failed",
        "charge.refunded",
        "charge.captured",
        "charge.updated",
    ),
    "checkout.session": (
        "checkout.session.completed",
        "checkout.session.expired",
        "checkout.session.async_payment_succeeded",
        "checkout.session.async_payment_failed",
    ),
    "customer": (
        "customer.created",
        "customer.updated",
        "customer.deleted",
    ),
    "subscription": (
        "customer.subscription.created",
        "customer.subscription.updated",
        "customer.subscription.deleted",
        "customer.subscription.paused",
        "customer.subscription.resumed",
        "customer.subscription.trial_will_end",  # 3 days before trial ends
    ),
    "invoice": (
        "invoice.created",
        "invoice.paid",
        "invoice.updated",
        "invoice.deleted",
        "invoice.finalized",
        "invoice.finalization_failed",
        "invoice.marked_uncollectible",
        "invoice.payment_action_required",
        "invoice.payment_failed",
        "invoice.payment_succeeded",
        "invoice.sent",
        "invoice.upcoming",
        "invoice.voided",
    ),
    "payment_intent": (
        "payment_intent.created",
        "payment_intent.succeeded",
        "payment_intent.payment_failed",
        "payment_intent.canceled",
        "payment_intent.processing",
        "payment_intent.requires_action",
        "payment_intent.amount_capturable_updated",
    ),
    # below are the events that we don't care about but we store them
    "fee_refund": [],
    "application_fee": [],
    "account": [],
    "application": [],
    "balance": [],
    "billing_portal.configuration": [],
    "capability": [],
    "cash_balance": [],
    "dispute": [],
    "refund": [],
    "coupon": [],
    "credit_note": [],
    "customer_cash_balance_transaction": [],
    "tax_id": [],
    "tax_rate": [],
    "tax.settings": [],
    "file": [],
    "financial_connections.account": [],
    "identity.verification_session": [],
    "invoiceitem": [],
    "issuing.authorization": [],
    "issuing.dispute": [],
    "plan": [],
    "product": [],
    "subscription_schedule": [],
}

IGNORED_EVENT_TYPES = (  # we don't store these events
    "card",
    "bank_account",
    "issuing.card",
    "issuing.cardholder",
    "payment_link",
    "payout",
    "person",
    "promotion_code",
    "quote",
    "radar.early_fraud_warning",
    "reporting.report_run",
    "reporting.report_type",
    "review",
    "setup_intent",
    "scheduled_query_run",
    "sku",
    "source",
    "terminal.reader",
    "test_helpers.test_clock",
    "topup",
    "transfer",
    "mandate",
    "source_transaction",
    "billing_portal.session",
)
