# Generated by Django 4.2.17 on 2024-12-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('SU', 'Support'), ('SA', 'Sales'), ('FE', 'Feedback'), ('BI', 'Billing')], default='SU', max_length=2)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('IP', 'In Progress'), ('CO', 'Completed')], default='IP', max_length=2)),
                ('zendesk_ticket_id', models.IntegerField(blank=True, null=True)),
                ('slack_sent', models.BooleanField(default=False, help_text='Slack message sent to internal DoodleOps Support Channel.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts', to='app_api.api')),
            ],
        ),
    ]
