# Generated by Django 4.2.17 on 2024-12-07 19:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0, unique=True)),
                ('url_path', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'verbose_name_plural': 'API Apps',
            },
        ),
        migrations.CreateModel(
            name='APICounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('api_name', models.CharField(max_length=255)),
                ('number_of_calls', models.IntegerField(default=0)),
                ('date', models.DateField()),
                ('credits_used', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'API Calls Counter',
                'unique_together': {('username', 'api_name', 'date')},
            },
        ),
        migrations.CreateModel(
            name='API',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('html_template_path', models.CharField(help_text='The path to the HTML template rendered when the API is called.', max_length=100)),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('display_order', models.IntegerField(default=0)),
                ('url_path', models.CharField(help_text='The URL path to call this API from FastAPI', max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', help_text='Choose an HTTP method for this API', max_length=6)),
                ('active', models.BooleanField(default=True)),
                ('cost', models.IntegerField()),
                ('svg_icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('other_info', models.JSONField(blank=True, null=True)),
                ('api_app', models.ForeignKey(help_text='The API App this API belongs to.', on_delete=django.db.models.deletion.DO_NOTHING, related_name='apis', to='app_api.apiapp')),
            ],
            options={
                'verbose_name_plural': 'APIs',
            },
        ),
    ]
