# Generated by Django 4.2.17 on 2025-01-03 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='doc_url_path',
            field=models.CharField(blank=True, help_text='The URL path to the documentation of this API', max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='api',
            name='url_path',
            field=models.CharField(help_text='The URL path to call this API from FastAPI', max_length=255, unique=True),
        ),
    ]
