# Generated by Django 4.2.18 on 2025-03-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0002_api_doc_url_path_alter_api_url_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostOfLLMAppAI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redis_key_name', models.CharField(max_length=100, unique=True)),
                ('display_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('cost', models.IntegerField()),
                ('svg_icon_name', models.CharField(blank=True, max_length=100, null=True)),
                ('other_info', models.JSONField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Cost of LLMs APP AI',
            },
        ),
    ]
