# Generated by Django 4.2.18 on 2025-03-03 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_api', '0003_costofllmappai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api',
            name='cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
