# Generated by Django 4.2.17 on 2024-12-07 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value_type', models.CharField(choices=[('int', 'Integer'), ('str', 'String'), ('bool', 'Boolean'), ('float', 'Float'), ('datetime', 'Datetime'), ('json', 'JSON')], max_length=10)),
                ('int_value', models.IntegerField(blank=True, null=True)),
                ('str_value', models.TextField(blank=True, null=True)),
                ('bool_value', models.BooleanField(blank=True, null=True)),
                ('float_value', models.FloatField(blank=True, null=True)),
                ('datetime_value', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('json_value', models.JSONField(blank=True, help_text='Attention: JSON data must be valid, else Django Admin JS will not send it.', null=True)),
            ],
        ),
    ]
