# Generated by Django 4.2.17 on 2024-12-07 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditsBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('redis_key', models.CharField(max_length=255, unique=True)),
                ('redis_short_value', models.CharField(blank=True, max_length=255, null=True)),
                ('redis_long_value', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerCreditsBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expires', models.DateTimeField()),
                ('details', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PricingBuyCredit',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('price_in_cents', models.IntegerField(default=0)),
                ('credits', models.IntegerField(default=0)),
                ('display_order', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PricingBuySubscription',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price_in_cents', models.IntegerField(blank=True, null=True)),
                ('credits_monthly', models.IntegerField(blank=True, null=True)),
                ('is_monthly', models.BooleanField(default=False)),
                ('is_yearly', models.BooleanField(default=False)),
                ('display_order', models.IntegerField(default=0)),
                ('api_daily_call_limit', models.IntegerField(default=0, help_text='This is used to set new user daily call limit based on the subscription plan they purchased. If the subscription is canceled, the user will be downgraded to the default daily call limit, set in the Settings model.')),
                ('is_metered', models.BooleanField(default=False, help_text='This is the Enterprise plan.')),
            ],
        ),
        migrations.CreateModel(
            name='PricingBuySubscriptionTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.IntegerField(help_text='No of Credits consumed Start')),
                ('end', models.IntegerField(blank=True, help_text='No of Credits consumed End', null=True)),
                ('price_in_cents', models.DecimalField(decimal_places=2, default=0.0, help_text='Price in cents per Credit used.', max_digits=10)),
                ('flat_amount_in_cents', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='StripeEvent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('event_object', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('error', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StripeInvoice',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.IntegerField()),
                ('amount_due', models.IntegerField(help_text='Amount due in cents')),
                ('status', models.CharField(choices=[('open', 'Open'), ('draft', 'Draft'), ('paid', 'Paid'), ('payment_failed', 'Payment failed')], default='unpaid', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StripePaymentIntent',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created', models.IntegerField()),
                ('amount', models.IntegerField(help_text='Amount in cents')),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded')], default='unpaid', max_length=23)),
            ],
        ),
        migrations.CreateModel(
            name='StripeSubscriptionItem',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('subscription_id', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('current_period_start', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('current_period_end', models.IntegerField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('is_past_due', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('event_id', models.CharField(blank=True, max_length=100, null=True)),
                ('pricing_plan', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app_financial.pricingbuysubscription')),
            ],
        ),
    ]
