# Generated by Django 4.2.17 on 2024-12-07 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_financial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscriptionitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stripepaymentintent',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financial.stripeinvoice'),
        ),
        migrations.AddField(
            model_name='stripepaymentintent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stripeinvoice',
            name='price',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financial.pricingbuysubscription'),
        ),
        migrations.AddField(
            model_name='stripeinvoice',
            name='subscription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_financial.stripesubscriptionitem'),
        ),
        migrations.AddField(
            model_name='stripeinvoice',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stripeevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pricingbuysubscriptiontier',
            name='pricing_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing_plan_tiers', to='app_financial.pricingbuysubscription'),
        ),
        migrations.AddField(
            model_name='customercreditsbought',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credits', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='stripesubscriptionitem',
            index=models.Index(fields=['id'], name='app_financi_id_ab5a0f_idx'),
        ),
        migrations.AddIndex(
            model_name='stripepaymentintent',
            index=models.Index(fields=['id'], name='app_financi_id_63d4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='stripeevent',
            index=models.Index(fields=['event_type', 'id'], name='app_financi_event_t_33c0d5_idx'),
        ),
    ]
