# Generated by Django 4.2.17 on 2025-01-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripesubscriptionitem',
            name='last_updated',
            field=models.DateTimeField(blank=True, help_text='This is used to keep a record and to determine who should get monthly credits for the yearly subscription. Task name: task_add_monthly_credits_to_yearly_subscriptions', null=True),
        ),
    ]
