# Generated by Django 4.2.17 on 2025-01-17 19:18

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_financial', '0003_stripesubscriptionitem_last_updated'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserFinancials',
            fields=[
            ],
            options={
                'verbose_name': 'User - Financial Info',
                'verbose_name_plural': 'Users - Financials Info',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('app_users.customuser',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterModelOptions(
            name='customercreditsbackup',
            options={'verbose_name': 'Backup - Customer Credits', 'verbose_name_plural': 'Backups - Customer Credits'},
        ),
        migrations.AlterModelOptions(
            name='customercreditsbought',
            options={'verbose_name': 'User - Credits Bought directly', 'verbose_name_plural': 'Users - Credits Bought directly'},
        ),
        migrations.AlterModelOptions(
            name='pricingbuycredit',
            options={'verbose_name': 'Stripe - Credit Plan', 'verbose_name_plural': 'Stripe - Credit Plans'},
        ),
        migrations.AlterModelOptions(
            name='pricingbuysubscription',
            options={'verbose_name': 'Stripe - Subscription Plan', 'verbose_name_plural': 'Stripe - Subscription Plans'},
        ),
        migrations.AlterModelOptions(
            name='pricingbuysubscriptiontier',
            options={'verbose_name': 'Stripe - Subscription Tier', 'verbose_name_plural': 'Stripe - Subscription Tiers'},
        ),
        migrations.AlterModelOptions(
            name='stripeevent',
            options={'verbose_name': 'Stripe - Event', 'verbose_name_plural': 'Stripe - Events'},
        ),
        migrations.AlterModelOptions(
            name='stripeinvoice',
            options={'verbose_name': 'Stripe - Invoice', 'verbose_name_plural': 'Stripe - Invoices'},
        ),
        migrations.AlterModelOptions(
            name='stripepaymentintent',
            options={'verbose_name': 'Stripe - Payment Intent', 'verbose_name_plural': 'Stripe - Payment Intents'},
        ),
        migrations.AlterModelOptions(
            name='stripesubscriptionitem',
            options={'verbose_name': 'Stripe - Subscription Item', 'verbose_name_plural': 'Stripe - Subscription Items'},
        ),
        migrations.AlterField(
            model_name='customercreditsbought',
            name='details',
            field=models.TextField(blank=True, help_text='Details of the purchase.', null=True),
        ),
        migrations.CreateModel(
            name='EnterpriseUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enterpriseuser_last_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User - is Enterprise ',
                'verbose_name_plural': 'Users - are Enterprise',
            },
        ),
        migrations.CreateModel(
            name='CustomerCreditsRemoved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credits', models.IntegerField(default=0, help_text='Number of Credits removed.')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('backend_details', models.TextField(blank=True, help_text='This is not displayed to the user.', null=True)),
                ('public_details', models.TextField(blank=True, help_text='This is displayed to the user.', null=True)),
                ('removal_type', models.CharField(choices=[('bought', 'Bought'), ('subscription', 'Subscription')], default='bought', max_length=100)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_removed_last_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_credits_removed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User - Credits Removed by Admin/Staff',
                'verbose_name_plural': 'Users - Credits Removed by Admin/Staff',
            },
        ),
    ]
