# Generated by Django 4.2.18 on 2025-03-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_financial', '0004_customuserfinancials_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseuser',
            name='max_credits_limit_per_month',
            field=models.IntegerField(default=5000),
        ),
    ]
